name: Build 3105 iOS

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-15

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Select Xcode
        run: |
          sudo xcode-select -s /Applications/Xcode_26.3.app/Contents/Developer
          xcodebuild -version

      - name: Check project
        run: |
          cd 3105-main
          ls -la
          xcodebuild -list -project ThreeOneOSFive.xcodeproj

      - name: Build
        run: |
          cd 3105-main

          xcodebuild \
            -project ThreeOneOSFive.xcodeproj \
            -target 3105 \
            -sdk iphoneos \
            -configuration Release \
            -derivedDataPath build \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            build

      - name: Find app
        run: |
          find 3105-main/build -name "*.app" -type d -print

      - name: Package app
        run: |
          mkdir -p output

          APP_PATH=$(find 3105-main/build/Build/Products \
            -name "*.app" \
            -type d | head -n 1)

          if [ -z "$APP_PATH" ]; then
            echo "❌ ไม่พบ .app"
            exit 1
          fi

          cp -R "$APP_PATH" output/3105.app

      - name: Upload build
        uses: actions/upload-artifact@v4
        with:
          name: 3105-iOS-Build
          path: output/3105.app
